### ISSUE TITLE
Usersnap Feedback - Edit profile button does not show up unless I sign out and sign in again. [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#341] opened 2019-03-26 14:34 UTC
**Sender**: scottowenfletcher@gmail.com
**Comment**: Edit profile button does not show up unless I sign out and sign in again. I've tried this with two different accounts.
[Open #312 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/312)

<a href='https://usersnappublic.s3.amazonaws.com/2019-03-26/15-33/5c948aa5-7e4a-49be-ac56-017a6ffc767a.png'>![Usersnap Feedback - Edit profile button does not show up unless I sign out and sign in again. (...)](https://usersnappublic.s3.amazonaws.com/2019-03-26/15-33/98728050-05de-412f-adb5-9728ee53aafe.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-03-26/15-33/5c948aa5-7e4a-49be-ac56-017a6ffc767a.png'>Download original image</a>

**Browser**: Chrome 73 (Windows 10)
**Referer**: [https://participedia.xyz/users/110904](https://participedia.xyz/users/110904)
**Screen size**: 1280 x 720 **Browser size**: 1707 x 771

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment] 2019-03-27 21:40
I cannot reproduce this bug on macbook, chrome. tried admin and public user accounts to test, and I see the edit profile button on first attempt to view profile for both accounts. @ascott could you try to repro?

**Comment by ascott** [comment] 2019-03-27 21:49
yeah, this happened for me as well. not sure what the issue would be without digging in further. since there is a work around, (logging out and logging in again) i would suggest that we not prioritize a fix for this since we are working on the new site.

**Comment by jesicarson** [comment] 2019-03-27 21:51
yep focus on staging. just wanted to verify the bug before prompting people to edit their profiles actively to deal with the public facing emails on xyz. if its buggy, we won't even bother to do that. thanks!

**Closed as completed** 2019-05-15 18:49 UTC
