### ISSUE TITLE
Usersnap Feedback - It's confusing where you're supposed to click. Can we make this whole box [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#414] opened 2019-05-14 22:10 UTC
**Sender**: scottowenfletcher@gmail.com
**Comment**: It's confusing where you're supposed to click. Can we make this whole box click-able? Maybe I'm just simple minded, but it took me a while to figure out that I had to click on the words "Click to select"
[Open #119 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/119)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/00-09/3b802e24-223c-47fd-8c98-11844753e8fc.png'>![Usersnap Feedback - It's confusing where you're supposed to click. Can we make this whole box (...)](https://usersnappublic.s3.amazonaws.com/2019-05-15/00-09/4137b611-d1c9-4fe4-96e2-9a4beabe8cf2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/00-09/3b802e24-223c-47fd-8c98-11844753e8fc.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/case/new?full=1](https://ppedia-stage.herokuapp.com/case/new?full=1)
**Screen size**: 1600 x 900 **Browser size**: 1600 x 731

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment] 2019-05-14 22:11
ideally you could click the big "+" sign - I think that's the first place people would click

**Comment by jesicarson** [comment] 2019-05-15 21:34
duplicate of #443

**Closed as completed by jesicarson** 2019-05-15 21:34 UTC
Labels: design-feedback
