### ISSUE TITLE
Usersnap Feedback - Error doing search (I copied and pasted the title of the case from .net)

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#148] opened 2018-04-13 01:34 UTC
**Sender**: scottowenfletcher@gmail.com
**Comment**: Error doing search (I copied and pasted the title of the case from .net)
[Open #162 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/162)

<a href='https://usersnappublic.s3.amazonaws.com/2018-04-13/03-33/f5c142b1-c360-445b-bfee-2711fccfa751.png'>![Usersnap Feedback - Error doing search (I copied and pasted the title of the case from .net)](https://usersnappublic.s3.amazonaws.com/2018-04-13/03-33/83265a8b-8708-47f0-a86d-f299a0c9f8ef.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-04-13/03-33/f5c142b1-c360-445b-bfee-2711fccfa751.png'>Download original image</a>

**Browser**: Chrome 65 (Windows 10)
**Referer**: [https://participedia.xyz/?query=Public%20Engagement%20Project%20on%20Pandemic%20Influenza%20Vaccine%20Priorities%20(2005-2007)](https://participedia.xyz/?query=Public%20Engagement%20Project%20on%20Pandemic%20Influenza%20Vaccine%20Priorities%20(2005-2007))
**Screen size**: 1280 x 720 **Browser size**: 1422 x 600

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by scottofletcher** [comment] 2018-04-23 21:57
Duplicate of #149

**Comment by jesicarson** [comment] 2018-06-19 17:27
@scottofletcher if you re-did this search from the homepage and it worked, then this issue can be closed (covered by #149 and https://github.com/participedia/frontend/issues/836). If it didn't return results, indicating missing content that should have been imported from .net, then keep this open. Thanks!

**Comment by scottofletcher** [comment] 2018-06-19 23:31
I think this was fixed - turned out the search function was returning results by relevance in the wrong order haha

**Closed as completed by scottofletcher** 2018-06-19 23:31 UTC
