### ISSUE TITLE
Usersnap Feedback - 2020-07-13 05:40:26

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1098] opened 2020-07-13 03:40 UTC
[Open #790 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/790)

<a href='https://usersnappublic.s3.amazonaws.com/2020-07-13/05-40/e403cd27-4709-490f-9878-5b2d8bfbb8a8.png'>![Usersnap Feedback - 2020-07-13 05:40:26](https://usersnappublic.s3.amazonaws.com/2020-07-13/05-40/1dcf23b7-0ee6-4d2a-b13e-43d27138dc36.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-07-13/05-40/e403cd27-4709-490f-9878-5b2d8bfbb8a8.png'>Download original image</a>

**Browser**: Safari 13 (Macintosh)
**Referer**: [https://participedia.net/case/4723](https://participedia.net/case/4723)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 837

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment] 2020-07-14 18:29
Not clear what the issue is here, and no contact listed. Closing.

**Closed as completed by jesicarson** 2020-07-14 18:29 UTC
