### ISSUE TITLE
Usersnap Feedback - Value should display as "Stratified Random Sample" (not 'stratified' so th[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1092] opened 2020-07-01 20:02 UTC
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: Value should display as "Stratified Random Sample" (not 'stratified' so that it matches the option in the data entry form
[Open #784 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/784)

<a href='https://usersnappublic.s3.amazonaws.com/2020-07-01/22-02/5e1543cf-f9f4-4173-8654-aa67c02556bb.png'>![Usersnap Feedback - Value should display as "Stratified Random Sample" (not 'stratified' so th(...)](https://usersnappublic.s3.amazonaws.com/2020-07-01/22-02/dfef4ae3-dab7-49b4-8e5f-430e255cc365.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-07-01/22-02/5e1543cf-f9f4-4173-8654-aa67c02556bb.png'>Download original image</a>

**Browser**: Firefox 77 (Windows 10)
**Referer**: [https://participedia.net/case/6671](https://participedia.net/case/6671)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1045

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by paninee** [comment] 2020-08-05 19:28
Duplicate of https://github.com/participedia/usersnaps/issues/1093

**Closed as completed by paninee** 2020-08-05 19:28 UTC
Labels: bug, [i18n] internationalization
