### ISSUE TITLE
[USERSNAP] Here's the one that's not hidden that had 2 duplicates

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1843] opened 2022-09-16 16:47 UTC
**Sender**: slasors@mcmaster.ca
**Taken at**: https://participedia.net/case/8543/edit
**Fields**:
- Add a comment: Here&#39;s the one that&#39;s not hidden that had 2 duplicates

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/9d95e222-9d93-453f-9429-43ceab77fb8c-annotated_93d396a0-5c6e-41cd-8530-486d8f470ff6.png?etag=466a5a9f78c74e24913dad1d2df65e5d)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/9d95e222-9d93-453f-9429-43ceab77fb8c-annotated_93d396a0-5c6e-41cd-8530-486d8f470ff6.png?etag=466a5a9f78c74e24913dad1d2df65e5d)*

**Browser**: Chrome 105 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1065x688
**[Open #1526 in Usersnap](https://app.usersnap.com/l/feedback/b18a6e52-0f22-4739-a6fe-75703f7a4fbd?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment] 2022-09-16 17:09
here are the hidden duplicates

https://participedia.net/case/8542
https://participedia.net/case/8537

**Comment by jesicarson** [comment] 2022-09-16 17:12
My test entry: https://participedia.net/case/8545 (published without previewing first, added title and image only) did not create duplicates. 

Pretty sure this is a connectivity issue on sarah's end, not a bug. but @paninee could you look at this when you have a minute? thanks!

**Comment by jesicarson** [comment] 2022-09-16 18:10
@paninee however, sarah tested today and produced duplicates... flagging as a bug and moving to TODO

Here are the links:
https://participedia.net/case/8546/
https://participedia.net/case/8547/

**Comment by paninee** [comment] 2022-10-14 04:41
@jesicarson what's the reproduction steps on this one?

1. create new entry
2. preview
3. public from preview

Are those the steps?

**Comment by jesicarson** [comment] 2022-10-14 18:13
@paninee i emailed sarah and cc'd you

**Comment by jesicarson** [comment] 2022-10-17 17:19
Confirmed by email that, those are the steps Sarah took: Create, preview, publish.

**Comment by paninee** [comment] 2023-03-27 09:03
I think this one an old case before we fixed the issue. The cases is created on Sept 2022.

**Closed as completed** 2023-05-03 13:16 UTC
Labels: bug
