### ISSUE TITLE
[USERSNAP] Hi, I wanted to let you know about a possible bug: when I am on any of the collections pages and try to click on a case, I am taken to an 'edit' page automatically. If I am not logged in, I am taken to a log in page. Basically, I can't access...

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1826] opened 2022-09-07 08:17 UTC
**Sender**: kathleen.h.rawlings@gmail.com
**Taken at**: https://participedia.net/search?selectedCategory=collections
**Fields**:
- Add a comment: Hi, I wanted to let you know about a possible bug: when I am on any of the collections pages and try to click on a case, I am taken to an &#39;edit&#39; page automatically. If I am not logged in, I am taken to a log in page. Basically, I can&#39;t access any of the collections articles in a normal way. Thanks for the awesome site! - Kathy

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/cdcbcd7b-ecd2-4ca2-b4f1-22fd389932c5-annotated_8341edd4-691d-4726-8a95-2ab6b81d992a.png?etag=1700897e79b0029b3a799e6add3ace81)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/cdcbcd7b-ecd2-4ca2-b4f1-22fd389932c5-annotated_8341edd4-691d-4726-8a95-2ab6b81d992a.png?etag=1700897e79b0029b3a799e6add3ace81)*

**Browser**: Chrome 104 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1070x710
**[Open #1509 in Usersnap](https://app.usersnap.com/l/feedback/d48a847d-8be5-47d5-a9a3-923b7b2bd9d6?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment] 2022-09-07 17:42
@paninee i just tested this and i am also having the same result. Looks like when you select an entry on a collection it takes you to the edit view instead of the reader view. please have a look. thanks

**Comment by jesicarson** [comment] 2022-09-07 17:44
The issue is not happening on search results outside of collections. So only collections have this issue.

**Comment by jesicarson** [comment] 2022-10-13 16:53
covered by #1853 closing this one

**Closed as completed by jesicarson** 2022-10-13 16:53 UTC
Labels: bug
