### ISSUE TITLE
Usersnap Feedback - when I changed the original submission information, it changed the most re[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1343] opened 2021-02-11 03:11 UTC
**Sender**: jgakhal@alumni.ubc.ca
**Comment**: when I changed the original submission information, it changed the most recent date as well
[Open #1028 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1028)

<a href='https://usersnappublic.s3.amazonaws.com/2021-02-11/04-11/3a246c06-8632-4273-8e59-0cfe9f176e10.png'>![Usersnap Feedback - when I changed the original submission information, it changed the most re(...)](https://usersnappublic.s3.amazonaws.com/2021-02-11/04-11/1a44a82c-d375-4c8a-8ba7-50f4fd57a23d.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-02-11/04-11/3a246c06-8632-4273-8e59-0cfe9f176e10.png'>Download original image</a>

**Browser**: Safari 12 (macOS Mojave)
**Referer**: [https://participedia.net/case/7267](https://participedia.net/case/7267)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 837

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment] 2021-02-12 20:51
@paninee could you take a quick look at this? could be resulting from the recent changes you made to the contributor history drop down. thanks!

**Comment by paninee** [comment] 2021-03-18 02:52
@jesicarson I couldn't reproduce this. A few weeks ago I fixed an issue related to the original submission date. Was it possible it was fixed with that change already? Do you mind verifying again?

**Comment by jesicarson** [comment] 2021-03-18 18:14
I can't reproduce either. Closing.

**Closed as completed by jesicarson** 2021-03-18 18:14 UTC
Labels: bug
