### ISSUE TITLE
Usersnap Feedback - I entered the method name, but this number appears instead "Decision-focus[...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1052] opened 2020-05-13 16:16 UTC
**Sender**: pscully@clearviewconsultingllc.com
**Comment**: I entered the method name, but this number appears instead "Decision-focused Public Engagement Table” (DPET)" - It would be good if we can fix this ASAP b/c it is connected to two of our Covid-19 entries
[Open #745 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/745)

<a href='https://usersnappublic.s3.amazonaws.com/2020-05-13/18-15/c1ea66ef-3f3f-4738-8406-1f2237521f9c.png'>![Usersnap Feedback - I entered the method name, but this number appears instead "Decision-focus(...)](https://usersnappublic.s3.amazonaws.com/2020-05-13/18-15/975939f1-c353-4ab1-a2a3-5741669a43d2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-05-13/18-15/c1ea66ef-3f3f-4738-8406-1f2237521f9c.png'>Download original image</a>

**Browser**: Firefox 76 (Windows 10)
**Referer**: [https://participedia.net/organization/6542](https://participedia.net/organization/6542)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1045

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment] 2020-05-13 16:57
weird! i'll take a look at this one.

**Comment by ascott** [comment] 2020-05-27 19:55
@paninee could you take a look at this one please?

**Comment by paninee** [comment] 2020-05-28 04:32
@ascott Cannot reproduce. I see the method title.
![image](https://user-images.githubusercontent.com/29439995/83099194-81e8a200-a061-11ea-9c47-201d6ad74f4d.png)

**Comment by paninee** [comment] 2020-05-28 06:03
Reopens. Re-produced while testing https://github.com/participedia/usersnaps/issues/1057

**Comment by paninee** [comment] 2020-07-12 20:59
Fixed with https://github.com/participedia/api/issues/888

**Closed as completed by paninee** 2020-07-12 20:59 UTC
Labels: bug, P1
