### ISSUE TITLE
Usersnap Feedback - These fields are awesome!

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#50] opened 2017-06-17 22:41 UTC
**Sender**: scottowenfletcher@gmail.com
**Comment**: These fields are awesome!
[Open #64 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/64)

<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/00-41/8fe2dd0d-b4f4-4a21-9bbd-22d580689e78.png'>![Usersnap Feedback - These fields are awesome!](https://usersnappublic.s3.amazonaws.com/2017-06-18/00-41/1e92c722-214c-46e9-91ef-1a6e6cb7f344.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-06-18/00-41/8fe2dd0d-b4f4-4a21-9bbd-22d580689e78.png'>Download original image</a>

**Browser**: Chrome 58 (Windows 10)
**Referer**: [https://participedia.xyz/case/4557/edit](https://participedia.xyz/case/4557/edit)
**Screen size**: 1280 x 720 **Browser size**: 1280 x 590

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by andreadelrio** [comment] 2017-08-05 02:34
Closing as this is not a bug or enhancement request.

**Closed as completed** 2017-08-05 02:34 UTC
