### ISSUE TITLE
Usersnap Feedback - Clicking 'Do Full Version' should not wipe everything out. I like how it's [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#483] opened 2019-05-15 21:32 UTC
**Sender**: scottowenfletcher@gmail.com
**Comment**: Clicking 'Do Full Version' should not wipe everything out. I like how it's set up on XYZ: you can complete the Quick Submit form and then hit 'Do Full Version' and complete the rest of it. otherwise users are disincentivized to do the full version: they'd have to finish Quick Submit, publish, then hit edit, scroll down to the bottom of the page, hit Do Full Version and then go through the rest of the form.
[Open #186 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-201-a37e4cf6/186)

<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/23-32/01ce48f6-0175-4e56-a126-8cf578911884.png'>![Usersnap Feedback - Clicking 'Do Full Version' should not wipe everything out. I like how it's (...)](https://usersnappublic.s3.amazonaws.com/2019-05-15/23-32/73d9b6e3-a4a3-4f05-be91-f289f794c436.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-05-15/23-32/01ce48f6-0175-4e56-a126-8cf578911884.png'>Download original image</a>

**Browser**: Firefox 66 (Windows 10)
**Referer**: [https://ppedia-stage.herokuapp.com/case/new](https://ppedia-stage.herokuapp.com/case/new)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 877

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment] 2019-05-15 21:35
duplicate of #479

**Closed as completed by jesicarson** 2019-05-15 21:35 UTC
