### ISSUE TITLE
Phraseapp / Translation Plugin Bug

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#887] opened 2019-10-07 19:53 UTC
Viewing a case in French. If you have a translation plugin, clicking it to "translate this page" and see the narrative in French, results in the data reverting back to english.

**Comment by jesicarson** [comment] 2019-10-07 19:54
@ascott this needs to be addressed before Wednesday, Oct 16th, as there will be a Privy Council demo going on that day. Thanks! Let me know what you need.

**Comment by jesicarson** [comment] 2019-10-08 16:16
related (from pat) https://github.com/participedia/usersnaps/issues/888 https://github.com/participedia/usersnaps/issues/889

**Comment by jesicarson** [comment] 2019-10-08 16:24
i'm not actually sure if this is something we can control or fix?
so we can't necessarily offer a way for people to see the narrative in the language matching the site UI, can we? 
and I cant seem to get the plugin to show up on reader pages to test it, but on the homepage it shows up for me, there are some options... maybe if the user changed the language settings to translate english to french, it would work on reader (ie: leave the french UI / static text alone, and only translate the narrative from english to french)?
![Screen Shot 2019-10-08 at 9 21 42 AM](https://user-images.githubusercontent.com/13560530/66413964-510e0c80-e9ad-11e9-8f66-a6c22f367deb.png)

**Comment by jesicarson** [comment] 2019-10-08 17:14
AH! Got the bug to show up for me on the homepage (duh! there's user entered text in the entry titles).
OK so yes, I changed the language to translate english to french, and then clicked translate. It worked great on the entry titles and seems to have left the static text alone on entries... but it translated the map overlay text from french to english??? wierd. maybe we're confusing the plugin with phraseap somehow? 
Is it possible to anticipate this interaction and plan for it within our own systems? Like if a translation plugin is used, can we block it from translating the static text/ui? The other option is to build in machine translation of user entered text to automatically occur when the language drop down is used (however there is a big cost associated with this, isn't that right?) not sure how to address this.. 
![Screen Shot 2019-10-08 at 10 09 54 AM](https://user-images.githubusercontent.com/13560530/66417029-fe841e80-e9b3-11e9-9ef3-c1a6939a7a9c.png)

**Comment by ascott** [comment] 2019-10-08 20:52
i haven't been able to reproduce this, is there a specific plugin you are using to translate the page? perhaps i don't have it installed 🤔

**Comment by ascott** [comment] 2019-10-08 20:54
ah, i'm assuming it's this plugin? https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb

**Comment by ascott** [comment] 2019-10-08 20:59
> OK so yes, I changed the language to translate english to french, and then clicked translate. It worked great on the entry titles and seems to have left the static text alone on entries... but it translated the map overlay text from french to english??? wierd. maybe we're confusing the plugin with phraseapp somehow?

@jesicarson it looks like it translated some of the map overlay, but interpreted some words as titles or something and left them as is. Some of the map overlay text is in English and some is in French.

**Comment by ascott** [comment] 2019-10-08 21:02
using this [plugin](https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb), I was able to translate a reader page as expected: 

First, selected French from our language drop down
<img width="1680" alt="Screenshot 2019-10-08 13 56 48" src="https://user-images.githubusercontent.com/130878/66432879-ed4b0a00-e9d3-11e9-985f-39c2190f472b.png">

Then clicked on the Google Translate extension icon and clicked Translate This Page
<img width="1680" alt="Screenshot 2019-10-08 13 56 53" src="https://user-images.githubusercontent.com/130878/66432903-fb008f80-e9d3-11e9-9293-6cce9eaed49e.png">

All the text is in french at this point, all being machine translated by the Google Translate extension.
<img width="1680" alt="Screenshot 2019-10-08 13 57 03" src="https://user-images.githubusercontent.com/130878/66432974-23888980-e9d4-11e9-80eb-361f901ebf29.png">

Ideally we would handle the machine and human translation of the user entered text in our system, negating the need to users to use their own translate extension/plugin, but that translation project hasn't been prioritized yet.

**Comment by jesicarson** [comment] 2019-10-09 18:08
D&T Update:

- There is no way to block plugins from translating our static text that has already been translated by phraseapp. We can't control plugin settings for users, they'll have to take care of these settings manually. 

- Implementing a system for translation of user entered text is the only way to solve this problem. This is in our dev queue, but will come in a few months after some other issues are dealt with.

- For now, we will implement an FAQ item that explains why the language drop down on our site only translates the site UI. Jesi will draft this text and make a new issue in api for this.

**Comment by ascott** [comment] 2019-11-08 18:30
closing this issue, since it's related to browser extensions and not a bug on our end.

**Closed as completed by ascott** 2019-11-08 18:30 UTC
Labels: bug, P1
