### ISSUE TITLE
Usersnap Feedback - I am unable to get past this point to see the text of my method.  At this [...]

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#333] opened 2019-03-20 12:46 UTC
**Sender**: fredgohlke.29@gmail.com
**Comment**: I am unable to get past this point to see the text of my method.  At this point, I'm in an endless loop/

Fred Gohlke
[Open #307 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/307)

<a href='https://usersnappublic.s3.amazonaws.com/2019-03-20/13-41/3e2efbaf-74a6-4269-8e46-9547f0dde67b.png'>![Usersnap Feedback - I am unable to get past this point to see the text of my method.  At this (...)](https://usersnappublic.s3.amazonaws.com/2019-03-20/13-41/e7067a64-45d3-434b-be4f-eaa1d519aa96.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-03-20/13-41/3e2efbaf-74a6-4269-8e46-9547f0dde67b.png'>Download original image</a>

**Browser**: Edge 17 (Windows 10)
**Referer**: [https://participedia.xyz/method/5651](https://participedia.xyz/method/5651)
**Screen size**: 1280 x 720 **Browser size**: 1280 x 603

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment] 2019-03-20 17:53
Scott previously published this on Fred's behalf: https://participedia.xyz/method/151
I have emailed Fred, and will hide the blank method he got stuck on. 
I couldn't reproduce a bug on Fred's method, so closing this issue.

**Closed as completed by jesicarson** 2019-03-20 17:53 UTC

**Comment by jesicarson** [comment] 2019-03-20 17:54
Fred's user profile for reference:  https://participedia.xyz/users/417849
