### ISSUE TITLE
Usersnap Feedback - Method not loading. I've been stuck on this page for a very long time...

### ISSUE THREAD

**Issue by davidascher** [participedia/usersnaps#231] opened 2018-07-17 21:37 UTC
**Sender**: scottowenfletcher@gmail.com
**Comment**: Method not loading. I've been stuck on this page for a very long time...
[Open #244 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/244)

<a href='https://usersnappublic.s3.amazonaws.com/2018-07-17/23-37/22672e84-7652-4d27-b8f8-d2dcd03a6bfa.png'>![Usersnap Feedback - Method not loading. I've been stuck on this page for a very long time...](https://usersnappublic.s3.amazonaws.com/2018-07-17/23-37/b52f8147-55fd-47e7-b654-d984b167f68c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-07-17/23-37/22672e84-7652-4d27-b8f8-d2dcd03a6bfa.png'>Download original image</a>

**Browser**: Chrome 67 (Windows 10)
**Referer**: [https://participedia.xyz/method/538](https://participedia.xyz/method/538)
**Screen size**: 1280 x 720 **Browser size**: 1920 x 809

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment] 2018-07-31 18:25
@scottofletcher what is the title of method 538? Thanks

**Comment by jesicarson** [comment] 2018-07-31 18:30
Interesting, checked method/530 - 539 and they all don't load. Methods 529 and 540 DO load. Not sure what this is - my only guess is that these were deleted on .net (maybe spam) but that doesn't explain why they'd be ported over to xyz. Will have to wait for @dethe to get to it. Maybe it will be fixed after his ongoing framework overhaul.

**Comment by scottofletcher** [comment] 2018-07-31 22:10
Method 538 is "Endangered Species Act Section 10 Conservation Planning"

**Comment by scottofletcher** [comment] 2018-07-31 22:11
It's actually a tool/technique but I don't know if that changes anything

**Comment by jesicarson** [comment] 2018-08-01 15:45
@scottofletcher did the not loading problem begin after you edited the method in question? Looks like the title is different/ shorter now on xyz:

![screen shot 2018-08-01 at 8 44 05 am](https://user-images.githubusercontent.com/13560530/43532507-200ec7b4-9567-11e8-9595-8566909630cf.png)

**Comment by ascott** [comment] 2019-03-14 01:05
there are a few cases/methods with this error. 

```json
{
  "OK": false,
  "error": {
    "name": "QueryResultError",
    "stack": "QueryResultError: 0\n    at new QueryResultError (/app/node_modules/pg-promise/lib/errors/queryResult.js:122:24)\n    at Query.ctx.db.client.query (/app/node_modules/pg-promise/lib/query.js:191:41)\n    at Query.handleReadyForQuery (/app/node_modules/pg/lib/query.js:126:10)\n    at Connection.<anonymous> (/app/node_modules/pg/lib/client.js:163:19)\n    at emitOne (events.js:96:13)\n    at Connection.emit (events.js:191:7)\n    at TLSSocket.<anonymous> (/app/node_modules/pg/lib/connection.js:118:12)\n    at emitOne (events.js:96:13)\n    at TLSSocket.emit (events.js:191:7)\n    at readableAddChunk (_stream_readable.js:178:18)\n    at TLSSocket.Readable.push (_stream_readable.js:136:10)\n    at TLSWrap.onread (net.js:561:20)",
    "message": "No data returned from the query.",
    "code": 0,
    "result": {
      "command": "SELECT",
      "rowCount": 0,
      "oid": null,
      "rows": [],
      "fields": [
        {
          "name": "results",
          "tableID": 0,
          "columnID": 0,
          "dataTypeID": 114,
          "dataTypeSize": -1,
          "dataTypeModifier": -1,
          "format": "text"
        }
      ],
      "_parsers": [
        null
      ],
      "rowAsArray": false
    },
    "query": "WITH full_thing AS ( SELECT \"methods\".*, COALESCE(images, '{}') AS images, COALESCE(\"methods\".files, '{}') files, COALESCE(\"methods\".videos, '{}') videos, COALESCE(\"methods\".tags, '{}') tags, COALESCE(\"methods\".links, '{}') links, texts.body, texts.title, texts.description, first_author('539') AS creator, last_author('539') AS last_updated_by, get_location('539') AS location,  bookmarked(\"methods\".type, '539', null) FROM \"methods\", get_localized_texts('539', 'en') AS texts WHERE \"methods\".id = '539' ) SELECT to_json(full_thing.*) results FROM full_thing ;",
    "received": 0
  }
}
```

**Comment by dethe** [comment] 2019-03-14 02:53
That trace looks like it is for the url `https://participedia.xyz/method/539` which I would not expect to work, since 539 is the id of an organization, not a method.

Re: method/530 - 539 not loading: 531 & 534 are cases, 532, 535-537, & 539 are organizations, and 533 doesn't appear to exist at all. This does leave 530 and 538 as legitimate problems loading methods, but keeps us from trying to debug non-problems.

Figuring out why methods are failing on prod will take some digging, I need to reproduce the prod environment on my local build, which I haven't had to do for awhile. For what it's worth, these methods appear to be failing in the current local build as well, although it is difficult to say if it is the same issue.

When I try it now, `https://participedia.xyz/method/538` does load with "Habitat Conservation Planning in the U.S." and `https://participedia.xyz/method/530` loads for me with "Model United Nations." So maybe @ascott has fixed these on the front-end?

**Comment by ascott** [comment] 2019-03-14 06:19
thanks for taking a look dethe. perhaps we should return a 404 rather than a 500 if there is no data returned for a given id? i think we could close this issue tho since the original referrer [url](https://participedia.xyz/method/538) does work.

**Closed as completed by ascott** 2019-03-14 06:19 UTC
Labels: bug
