### ISSUE TITLE
Usersnap Feedback - csv download only includes 20 results, need to include all results for the [...]

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1251] opened 2020-11-05 17:05 UTC
**Sender**: jesi.carson@gmail.com
**Comment**: csv download only includes 20 results, need to include all results for the query in the csv (not just the first 20 displayed)
[Open #940 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/940)

<a href='https://usersnappublic.s3.amazonaws.com/2020-11-05/18-05/e1750668-872c-4fc4-9b88-865d738a3e29.png'>![Usersnap Feedback - csv download only includes 20 results, need to include all results for the (...)](https://usersnappublic.s3.amazonaws.com/2020-11-05/18-05/46edb1b7-10c6-4092-a475-286cccdde8a9.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-11-05/18-05/e1750668-872c-4fc4-9b88-865d738a3e29.png'>Download original image</a>

**Browser**: Chrome 86 (Macintosh)
**Referer**: [https://participedia-homepage-2020.herokuapp.com/search?selectedCategory=organizations&sector=government](https://participedia-homepage-2020.herokuapp.com/search?selectedCategory=organizations&sector=government)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 698

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment] 2020-11-05 17:44
@paninee can you take a look at this please?

**Comment by jesicarson** [comment] 2020-11-05 17:59
Thanks. 

Same thing going on for methods (https://github.com/participedia/usersnaps/issues/1252) and also for cases. 

Also, looks like theres some kind of error in this csv for cases (this was the query: https://participedia-homepage-2020.herokuapp.com/search?selectedCategory=case&general_issues=business) see row 11:
![Screen Shot 2020-11-05 at 9 57 11 AM](https://user-images.githubusercontent.com/13560530/98278569-a1a7be80-1f4d-11eb-9677-377b51996cb0.png)

**Comment by paninee** [comment] 2020-11-10 14:22
Duplicate of https://github.com/participedia/usersnaps/issues/1252

**Closed as completed by paninee** 2020-11-10 14:22 UTC
Labels: P1
