### ISSUE TITLE
Only show pins on the map for the entries in the search results

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#1062] opened 2020-05-28 23:42 UTC
**Sender**: jesi.carson@gmail.com
**Comment**: Definitely not matching the map to search results.
[Open #755 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/755)

<a href='https://usersnappublic.s3.amazonaws.com/2020-05-29/01-42/a1258b70-a39b-43ad-a8d8-63329c603021.png'>![Usersnap Feedback - Definitely not matching the map to search results.](https://usersnappublic.s3.amazonaws.com/2020-05-29/01-42/0c73f9f3-d86d-4b22-8e24-02c2717e0723.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-05-29/01-42/a1258b70-a39b-43ad-a8d8-63329c603021.png'>Download original image</a>

**Browser**: Chrome 83 (Macintosh)
**Referer**: [https://participedia.net/?selectedCategory=organizations&query=%22citizens+assembly%22](https://participedia.net/?selectedCategory=organizations&query=%22citizens+assembly%22)
**Screen size**: 1680 x 1050 **Browser size**: 1679 x 939

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment] 2020-06-05 20:27
this seems to be working for filtered results, but not when using the query parameter.

<img width="1680" alt="Screen Shot 2020-06-05 at 1 22 33 PM" src="https://user-images.githubusercontent.com/130878/83919776-348ac580-a730-11ea-9f62-283c3b6db298.png">

<img width="1680" alt="Screen Shot 2020-06-05 at 1 22 12 PM" src="https://user-images.githubusercontent.com/130878/83919785-394f7980-a730-11ea-98b3-ede7259d5cbc.png">

**Comment by paninee** [comment] 2020-06-09 00:06
@ascott I can't reproduce the issue. I notice you're trying on prod, but this code isn't on prod yet. We still haven't merged the PR here https://github.com/participedia/api/pull/927.

![image](https://user-images.githubusercontent.com/29439995/84091786-5d1df400-a9aa-11ea-8af3-4c67f0c24372.png)

**Comment by paninee** [comment] 2020-06-10 17:35
Does not look right on prod. Re-open the issue.

**Closed as completed** 2020-06-17 06:11 UTC
Labels: bug, P1
