### ISSUE TITLE
Usersnap Feedback - this says select up to three ways but suddenly was only letting me to do one

### ISSUE THREAD

**Issue by ascott** [participedia/usersnaps#866] opened 2019-09-14 10:08 UTC
**Sender**: lucy.parry@canberra.edu.au
**Comment**: this says select up to three ways but suddenly was only letting me to do one
[Open #563 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/563)

<a href='https://usersnappublic.s3.amazonaws.com/2019-09-14/12-08/3354cfbd-992d-4ce0-891e-175df8ace639.png'>![Usersnap Feedback - this says select up to three ways but suddenly was only letting me to do one](https://usersnappublic.s3.amazonaws.com/2019-09-14/12-08/837196b9-4b7c-4d6b-963d-7571784f2ea4.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2019-09-14/12-08/3354cfbd-992d-4ce0-891e-175df8ace639.png'>Download original image</a>

**Browser**: Chrome 76 (Windows 10)
**Referer**: [https://participedia.net/case/5873/edit?full=1](https://participedia.net/case/5873/edit?full=1)
**Screen size**: 1366 x 768 **Browser size**: 1366 x 608

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ascott** [comment] 2019-09-23 03:10
@jesicarson i tested this field and can select and save up to 3 items. i tested on OsX 10.13/Chrome 76  and on Windows10/Chrome76, and everything is working as expected. are you able to reproduce?

**Comment by jesicarson** [comment] 2019-09-23 23:49
can't reproduce either. i'll ping lucy and see if she is still having trouble, maybe a connectivity glitch on her side. we can probably close this for now. will re-open if its still a problem.

**Closed as completed by jesicarson** 2019-09-23 23:49 UTC
Labels: bug
